### ISSUE TITLE
gazebo でロボットのトルク値が取れない（０が入っている）

### ISSUE THREAD

**Issue by s-noda** [start-jsk/rtmros_gazebo#114]
@mmurooka によるとトルク制御モードなら取れるとのことですが，今の速度制御モードではトルクが取れないようだということです．

何か方法はないでしょうか？

**Comment by mmurooka** [comment]
http://answers.gazebosim.org/question/6954/cannnot-get-joint-torque-while-setting-velocity/
の返事があって，速度制御モードだとトルクは取れないとJohn Hsuが言っているようです．

**Comment by YoheiKakiuchi** [comment]
https://github.com/start-jsk/rtmros_gazebo/pull/178
このコミットで出来るようになっていると思っていて、
https://github.com/start-jsk/rtmros_tutorials/pull/323
これでeffortがでるようになると思うのですが、確認してみてください。

**Comment by mmurooka** [comment]
出ていました．ありがとうございます．
ここはcloseして大丈夫だと思います．

**Comment by k-okada** [comment]
answersに出来たよ，と教えてあげましょう > @mmurooka

--
◉ Kei Okada

**Comment by mmurooka** [comment]
answersに報告しました．
