### ISSUE TITLE
gazeboのreal time factor がたまにすごく低くなる

### ISSUE THREAD

**Issue by mmurooka** [start-jsk/rtmros_gazebo#210]
@garaemon さんが，
Z640で，gazeboのreal time factorがたまに0.04になると報告していて，
僕の手元でも再現しました．
普段は0.8くらいで動いています．

放おっておくといつの間にかなおっていたり，上げなおすとなおったりして
何か原因の分かる方いらっしゃいますでしょうか．

**Comment by garaemon** [comment]
hrpsysを上げると0.9くらいになりました

**Comment by YoheiKakiuchi** [comment]
https://github.com/start-jsk/rtmros_gazebo/pull/199
これで、hrpsysとgazeboが同期をとるようになっているのでhrpsysが走っていないと遅くなります。

**Comment by garaemon** [comment]
@YoheiKakiuchi 
hrpsysが走ってないときにprintとかでたりしますか?
